"""add refunded status

Revision ID: 2299ad5e4ff0
Revises: 2e4ab9ac4643
Create Date: 2026-03-05 18:19:54.671576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2299ad5e4ff0'
down_revision: Union[str, None] = '2e4ab9ac4643'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
