"""add required_fields and customer_info

Revision ID: 4477b1cab840
Revises: 4a11a23aab1e
Create Date: 2026-03-07 17:59:19.223917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4477b1cab840'
down_revision: Union[str, None] = '4a11a23aab1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('customer_info', sa.JSON(), nullable=True))
    op.add_column('products', sa.Column('required_fields', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'required_fields')
    op.drop_column('orders', 'customer_info')
    # ### end Alembic commands ###
