"""create import_requests table

Revision ID: 8b67ef7856e5
Revises: ae6314c1e3ae
Create Date: 2026-03-05 21:09:02.098007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b67ef7856e5'
down_revision: Union[str, None] = 'ae6314c1e3ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('article_url', sa.String(length=1000), nullable=False),
    sa.Column('article_description', sa.Text(), nullable=True),
    sa.Column('screenshot_path', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('pending', 'contacted', 'in_progress', 'delivered', 'cancelled', name='importstatus'), nullable=True),
    sa.Column('staff_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_import_status', 'import_requests', ['status'], unique=False)
    op.create_index('idx_import_user', 'import_requests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_import_user', table_name='import_requests')
    op.drop_index('idx_import_status', table_name='import_requests')
    op.drop_table('import_requests')
    # ### end Alembic commands ###
