"""create orders table

Revision ID: a660a1570385
Revises: 98aa5aa47c14
Create Date: 2026-03-03 16:02:42.975257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a660a1570385'
down_revision: Union[str, None] = '98aa5aa47c14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'rejected', 'refunding', name='orderstatus'), nullable=False),
    sa.Column('screenshot_path', sa.String(length=255), nullable=True),
    sa.Column('staff_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_order_status', 'orders', ['status'], unique=False)
    op.create_index('idx_order_user', 'orders', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_order_user', table_name='orders')
    op.drop_index('idx_order_status', table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
