"""add parent_id and service_type to categories

Revision ID: ae6314c1e3ae
Revises: 2299ad5e4ff0
Create Date: 2026-03-05 20:15:18.930402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae6314c1e3ae'
down_revision: Union[str, None] = '2299ad5e4ff0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('service_type', sa.Enum('subscription', 'recharge', 'ebook', 'import_export', 'none', name='servicetype'), nullable=True))
    op.add_column('categories', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'categories', 'categories', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_column('categories', 'parent_id')
    op.drop_column('categories', 'service_type')
    # ### end Alembic commands ###
